server:
  port: 8989
  servlet:
    context-path: /hqxm
    jsp:
      init-parameters:
        development:  true
  tomcat:
    uri-encoding: UTF-8
spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp
  servlet:
    multipart:
      max-file-size: 50MB  		# 设置单个文件最大大小为10MB
      max-request-size: 100MB  	# 设置多个文件大小为100MB
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3307/cmfz?characterEncoding=UTF-8
    username: root
    password: root
#redis
  redis:
    host: 192.168.5.142
    port: 7000
mybatis:
  mapper-locations: classpath:com/yang/mapper/*.xml
  type-aliases-package: com.yang.entify
logging:
  level:
    root: info
    com.yang.dao: debug